ecommerceproject/Contact_app/urls.py
from . import views
from django.urls import path

app_name = 'Contact_app'

urlpatterns = [

    path('contact', views.contact, name='contact'),
]

ecommerceproject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [

    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist1/', views.wishlist, name='wishlist'),
    path('wishlist/', views.view_wishlist, name='view_wishlist'),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search_app.urls')),
    path('cart', include('cart.urls')),
    path('register/', include('registration.urls')),
    path('contact/', include('Contact_app.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/registration/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [

    path('', views.SearchResult, name='SearchResult'),
]

ecommerceproject/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodDetail, name='prodCatdetail'),

]

ecommerceproject/cart/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from shop.models import product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quatity

    def __str__(self):
        return '{}'.format(self.product)


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(product)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import product
from .models import Cart, CartItem, Wishlist
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    products = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except ObjectDoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=products, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except ObjectDoesNotExist:
        cart_item = CartItem.objects.create(
            product=products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=products, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=products, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')


def add_to_wishlist(request, product_id):
    product_instance = product.objects.get(pk=product_id)
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    wishlist.products.add(product_instance)
    wishlist1 = Wishlist.objects.filter(user=request.user).first()
    wishlist_items = wishlist1.products.all() if wishlist else []
    print(wishlist_items)
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_item = CartItem.objects.get(product_id=product_instance, cart=cart)
    cart_item.delete()
    return render(request, 'product_list.html', {'wishlist_items': wishlist_items})


@login_required
def remove_from_wishlist(request, product_id):
    product_instance = get_object_or_404(product, pk=product_id)

    wishlist_entry = Wishlist.objects.filter(user=request.user, products=product_instance).first()

    if wishlist_entry:
        wishlist_entry.delete()

    return redirect('cart:wishlist')


@login_required
def view_wishlist(request):
    wishlist = Wishlist.objects.filter(user=request.user).first()
    wishlist_items = wishlist.products.all() if wishlist else []
    return render(request, 'product_list.html', {'wishlist_items': wishlist_items})


@login_required
def wishlist(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    return render(request, 'product_list.html', {'wishlist_items': wishlist_items})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/f84c5636b8.js" crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@1,6..12,300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</div>
</body>
</html>

ecommerceproject/templates/cart.html
 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
     <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
 </svg>
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the Cart Page. Review and Buy !!!!!
{% endblock %}

{% block title%}
    Cart !!! Baby Smile
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is Empty</h1>
        <br>
        <p class="text-center">Please Click <a href="{% url 'shop:allProdCart' %}">Here </a></p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>

    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
                <tr>
                    <td><a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a></td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        Number:{{cart_item.product.id}}
                        <br>
                        Price: Rs {{cart_item.product.price}}
                        <br>
                        Quantity : {{cart_item.quantity}} X Rs {{cart_item}}
                    </td>
                    <td>
                        Rs {{cart_item.product.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                            <i class="fa fa-plus custom_icon"></i>&nbsp;</a>&nbsp
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa fa-minus custom_icon"></i></a>&nbsp
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                               <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                           </svg>

                            <i class="bi bi-trash-fill custom_icon"></i></a>&nbsp
                        <a href="{% url 'cart:add_to_wishlist' cart_item.product.id %}" class="btn btn-secondary btn-block my_custom_button">Add to wishlist</a>


                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa fa-minus custom_icon"></i></a>&nbsp
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                               <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                            </svg>
                            <i class="fa fa-trash custom_icon"></i></a>&nbsp
                        <a href="{% url 'cart:add_to_wishlist' cart_item.product.id %}" class="btn btn-secondary btn-block my_custom_button">Add to wishlist</a>



                    </td>
                </tr>
                    {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart item before proceeding with the payment
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>


        </div>
</div>
</div>
</div>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if Category %}
        {{ Category.decsription | truncatewords:155 }}
   {% else %}
        Welcome to Baby Smile where you can buy different items
   {% endif %}
{% endblock %}
{% block title %}
    {% if Category %}
        {{ Category.name }} - Baby Smile
    {% else %}
        See our new Collections - Baby Smile
    {% endif %}
{% endblock %}
{% block content %}
    {% if Category %}
<div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %} Our product collections"></a></p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{Category.image.url}}" alt="{{Category.name}}">
</div>
    <br>
<div>
    <h1 class="text-center my_title">{{Category.name}}</h1>
    <p class="text-justify">{{Category.description}}</p>
</div>
     {% else %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products"  width="500px" height="500px">
    <img class="my_image my_image_padding" src="{% static 'img/banner3.png' %}" alt="Our Products"  width="500px" height="500px">
</div>
<br>
<div>
    <h1 class="text-center my_title"> Our products collections </h1>
    <p class="text-justify"> At Baby Smile, our journey began with a simple passion for quality fabrics and timeless design.
Founded 2 years ago by Agastya, a visionary with a love for fashion,
we embarked on a mission to redefine comfort, style, and sustainability in the garment industry. </p>
</div>
     {% endif %}
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">

            <div class="card text-center" style="min-width:18rem;">

                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px" height="250">
                </a>


            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

ecommerceproject/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <title>Contact</title>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="logimage" width="100px" height="150px">
        <h4>We are happy to address you</h4>
    </center>
</head>
<body class="contact-background" style="background-color: #f5fffa">
    <div style="margin:80px">
        <h2 align="center">Contact Us</h2>
        <hr>
        <h4>Contact us directly if you have any queries. We will get in touch with you shortly.</h4>
        <hr>
        <br>
        <form method="post" action="" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <button type="submit" class="save btn btn-default">Submit</button>
        </form>
    </div>
</body>
</html>

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">



    <a href="#" class="text-center">Thrissur</a>
    <a href="#" class="text-center">/Ernakulam</a>
    <a href="#" class="text-center">/Kozhikode</a>
    <a href="#" class="text-center">/Trivandrum</a>
    <a href="#" class="text-center">/Pattanamtitta</a>
    <a href="#" class="text-center">/Kollam</a>
    <a href="#" class="text-center">/Attingal</a>
    <a href="#" class="text-center">/Kochi</a>
    <a href="#" class="text-center">/Kottayam</a>
    <a href="#" class="text-center">/Kannur</a>
    <a href="#" class="text-center">/Kasargod</a>
    <a href="#" class="text-center">/Kozhikode</a>
    <a href="#" class="text-center">/Palakkad</a>
    <a href="#" class="text-center">/Kunnamkulam</a>
    <a href="#" class="text-center">/Benguluru</a>
    <a href="#" class="text-center">/Chennai</a>
    <a href="#" class="text-center">/Delhi</a>
    <center>
        <!-- Add font awesome icons -->
        <a style="color: #3b5998;" href="#!" role="button">
            <i class="fab fa-facebook-f fa-lg"></i>
        </a>
        <a href="#" class="fa fa-pinterest"></a>
        <a href="#" class="fa fa-reddit"></a>
    </center>

<p class="text-center">
        © 2023 www.babysmile.com. All rights reserved.
    </p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allProdCat' %}"> <img src="{% static 'img/logo.png' %}" alt="logimage" width="100px" height="150px"></a>
  </center>
</header>

ecommerceproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your user name"><br><br>
    <input type="password" name="password" placeholder="Password"><br><br>
    <input type="submit">

</form>
{% for message in messages %}
{{message}}
{% endfor %}
</body>
</html>

ecommerceproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
          <li class="nav-item dropdown= {% if 'shop' in request.path %} active {% endif %}></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}


          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}" ><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
      </form>
          {% if user.is_authenticated %}
          <li>Hello {{user.username}} </li>
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
              <a class="nav-link" href="{% url 'register' %}">Sign Up</a>


              <a class="nav-link" href="{% url 'login' %}">Login</a>


              <a class="nav-link" href="{% url 'Contact_app:contact' %}">Contact Us</a>
          {% endif %}

    </div>
  </div>

</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description | truncatewords:155 }}
{% endblock %}

{% block title%}
    {% if Category %}
        {{product.name}} --- Baby Smile
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{product.Category.get_url}}" >{{product.Category}}</a> | {{product.name}}
        </p>
    </div>

    <div>


<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
             <img src="{{product.image.url}}" alt="{{product.name}}" style="width:250px;height:350px;">
        </div>
    </div>


    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
        </div>
     </div>
</div>
</div>
</div>
</div>
{% endblock %}

ecommerceproject/templates/product_list.html
{% load static %}
<!-- wishlist.html -->
<!DOCTYPE html>
<html>
<head>
    <title>My Wishlist</title>
    <center>
        <img src="{% static 'img/logo.png' %}" alt="logimage" width="100px" height="150px">
    </center>
</head>
<body>
    <h1>My Wishlist</h1>
    <ul>
        {% for item in wishlist_items %}
            <li>
                {{ item }} - {{ item.price }} -
<!--                <a href="{{item.get_absolute_url}}"><img src="{{item.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>-->
                    <a href="{% url 'cart:remove_from_wishlist' item.id %}">Remove</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

ecommerceproject/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Register and be a member in Baby Smile !!!!</h2>
<form class="form-register" action="register" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your user name"><br><br>
    <input type="text" name="first_name" placeholder="Enter your first name"><br><br>
    <input type="text" name="last_name" placeholder="Enter your last name"><br><br>
    <input type="email" name="email" placeholder="Enter your email"><br><br>
    <input type="text" name="Contact" placeholder="Enter your Contact Number"><br><br>
    <input type="password" name="password" placeholder="Password"><br><br>
    <input type="password" name="password1" placeholder="Password"><br><br>
    <input type="submit">

</form>
{% for message in messages %}
{{message}}
{% endfor %}
</body>
</html>

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   We have variety of products
{% endblock %}
{% block title %}
   Search
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">
        You have searched for : <b>"{{query}}"</b>
        </p>
    </div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">

            <div class="card text-center" style="min-width:18rem;">

                <a href="{{product.get_url}}">
                    <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px" height="250"> </a>


            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">
            0 results found
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerceproject/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
</head>
<body>
    <h2 style="text-align: center; color: red;"></h2style>We sent your message</h2>
    <p> You can send another in the<a href=" {% url 'Contact_app:contact' %}">Contact Page</a></p>
</body>
</html>